#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

CONF="hev-socks5-server"
PROG="/usr/bin/hev-socks5-server"

start_instance() {
	local section_name="$1"

	local enabled
	config_get_bool enabled "$section_name" "enabled" "0"
	[ "$enabled" -eq "1" ] || return 0

	local conffile
	config_get conffile "$section_name" "conffile"

	if [ -z "$conffile" ]; then
		echo "Error: 'conffile' not set for ${CONF} section '$section_name'"
		return 1
	fi
	if [ ! -f "$conffile" ]; then
		echo "Error: Configuration file '$conffile' not found for socks5 section '$section_name'"
		return 1
	fi

	# Use a unique procd instance name, e.g., "hev-socks5-server-main"
	procd_open_instance "$CONF-$section_name"
	procd_set_param command "$PROG" "$conffile"
	# Watch the specific YAML config file for changes for this instance
	procd_set_param file "$conffile"

	procd_set_param limits core="unlimited"
	procd_set_param limits nofile="1000000 1000000"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
}

start_service() {
	config_load "$CONF"
	config_foreach start_instance "$CONF"
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}
