# See /LICENSE for more information.
# This is free software, licensed under the GNU General Public License v2.

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI example app for js based luci
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all

PKG_LICENSE:=GPL-2.0
PKG_MAINTAINER:=Andreas Brau <ab@andi95.de>, \
	Duncan Hill <github.com@cricalix.net>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
# Makefile for luci-app-radius-mac
# Copyright (C) 2025 Your Name <your.email@example.com>
# This is free software, licensed under the Apache-2.0 License.

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI app for RADIUS MAC Authentication
LUCI_DEPENDS:=+luci-base +radius-mac
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-radius-mac
PKG_VERSION:=1.0
PKG_RELEASE:=1

# Use your name and email
PKG_MAINTAINER:=Your Name <your.email@example.com>
# Choose a license, Apache-2.0 is common for LuCI apps
PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
